services:
  kiosko-media-center:
    container_name: kiosko-media-center
    hostname: kiosko
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATA_DIR: /app/data
    volumes:
      - kiosko_volume:/app/data
    networks:
      - arrnet

volumes:
  kiosko_volume:
    external: true

networks:
  arrnet:
    external: true
