services:
  kiosko-media-center:
    container_name: kiosko-media-center
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATA_DIR: /app/data
      # Opcional: puedes quitarlas si ya configuras Plex desde /admin.html
      PLEX_URL: ${PLEX_URL}
      PLEX_TOKEN: ${PLEX_TOKEN}
    volumes:
      - ./data:/app/data