services:
  bbq:
    container_name: bbq
    hostname: bbq
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATA_DIR: /app/data
    volumes:
      - type: bind
        source: /var/mnt/nas/MHDisk/bbq
        target: /app/data
    networks:
      - arrnet

networks:
  arrnet:
    external: true
